Repository esmero/strawberryfield, pull requests merged in 2020-11, with the labels that each got.

#108 ISSUE-107: Make ::getDestinationUri() Smarter, better, suited for Self Deposit.
  src/StrawberryfieldFilePersisterService.php
Labels: Digital Preservation, Events and Subscriber, JSON Postprocessors, JSON Preprocessors, Symfony Services, Testing, enhancement, help wanted

#66 Issue 65: show node Edit tab if user has access to any Form Mode
  src/Controller/CustomNodeEditController.php
  strawberryfield.links.task.yml
  strawberryfield.routing.yml
Labels: enhancement

#110 ISSUE-109: Verbosity on demand
  src/Commands/JsonApiDrushCommands.php
  src/EventSubscriber/StrawberryfieldEventDeleteFileUsageDeleter.php
  src/EventSubscriber/StrawberryfieldEventInsertFileUsageUpdater.php
  src/EventSubscriber/StrawberryfieldEventInsertSubscriberDepositDO.php
  src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php
  src/EventSubscriber/StrawberryfieldEventPresaveSubscriberFilePersister.php
  src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php
  src/EventSubscriber/StrawberryfieldEventPresaveSubscriberVocabCreator.php
  src/Plugin/Action/StrawberryfieldJsonPatch.php
  strawberryfield.permissions.yml
  strawberryfield.services.yml
Labels: Events and Subscriber, Symfony Services, enhancement
