Repository esmero/strawberryfield, pull requests merged in 2020-01, with the labels that each got.

#54 ISSUE-53: Create new Config page for Solr settings
  config/schema/strawberryfield.schema.yml
  src/Form/ImportantSolrSettingsForm.php
  src/StrawberryfieldUtilityService.php
  strawberryfield.links.menu.yml
  strawberryfield.routing.yml
  strawberryfield.services.yml
Labels: enhancement, good first issue

#59 ISSUE-55: Title setter Service based on Metadata
  config/schema/strawberryfield.schema.yml
  src/EventSubscriber/StrawberryfieldEventPresaveSubscriberSetTitlefromMetadata.php
  strawberryfield.services.yml
Labels: Events and Subscriber, enhancement

#61 ISSUE-60: Automatic Natural order for uploaded files
  src/StrawberryfieldFilePersisterService.php
Labels: Documentation, JSON Postprocessors, Symfony Services, enhancement
