Repository esmero/strawberryfield, pull requests merged in 2021-09, with the labels that each got.

#199 ISSUE-197: Total refactor of the File Destination alter hook
  src/StrawberryfieldFilePersisterService.php
  strawberryfield.api.php
Labels: enhancement, JSON Postprocessors, Events and Subscriber, Digital Preservation, Symfony Services, Danger Mr Robinson

#198 ISSUE-196-custom-file-storage-path --- provide options to set relative paths for storage of managed strawberryfield files and digital object files (json)
  config/schema/strawberryfield.schema.yml
  src/EventSubscriber/StrawberryfieldEventInsertSubscriberDepositDO.php
  src/Form/FilePersisterServiceSettingsForm.php
  src/StrawberryfieldFilePersisterService.php
  src/StrawberryfieldUtilityService.php
  src/StrawberryfieldUtilityServiceInterface.php
Labels: Digital Preservation, Configuration, Danger Mr Robinson

#202 ISSUE-201: add Text Selection to OCR endpoint and Alto capabilities
  src/Controller/StrawberryfieldFlavorDatasourceSearchController.php
  strawberryfield.routing.yml
Labels: Typed Data and Search
