Repository esmero/strawberryfield, pull requests merged in 2023-04, with the labels that each got.

#266 ISSUE-265: Allow a workaround for dot files when composting
  config/schema/strawberryfield.schema.yml
  src/Form/FilePersisterServiceSettingsForm.php
  src/Plugin/QueueWorker/CompostQueueWorker.php
Labels: enhancement, question, Events and Subscriber, Danger Mr Robinson

#264 ISSUE-263: Improve HL for JOINS + Phrase Linking.
  config/schema/strawberryfield.schema.yml
  src/Controller/StrawberryfieldFlavorDatasourceSearchController.php
  src/EventSubscriber/StrawberryEventDeleteFlavorSubscriber.php
  src/EventSubscriber/StrawberryEventSaveFlavorSubscriber.php
  src/Plugin/search_api/processor/StrawberryFieldHighlight.php
  src/Plugin/search_api/processor/StrawberryFlavorAggregate.php
  src/Plugin/search_api/processor/StrawberryReduceReturn.php
  strawberryfield.module
Labels: Drupal Views, Typed Data and Search, Strawberry Flavor, UI/UX, Search API

#269 ISSUE-268: Modern JS (latest 112.0.5615.121 (Official Build) (x86_64)) and our wonky #states bug
  src/Form/keyNameProviderOverviewForm.php
Labels: bug
